-- ------------------------------------------------------------
--   THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY
-- ------------------------------------------------------------

-- ------------------------------------------------------------
--   src/BreitbandGraphics/breitbandgraphics.lua
-- ------------------------------------------------------------

--
-- Copyright (c) 2026, Mupen64 Organization (https://github.com/mupen64)
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

local BreitbandGraphics = {
    _VERSION = 'v2.0.1',
    _URL = 'https://codeberg.org/mupen64/ugui',
    _DESCRIPTION = 'Powerful rendering abstraction layer',
    _LICENSE = 'GPL-3',
}

-- ------------------------------------------------------------
--   src/BreitbandGraphics/types.lua
-- ------------------------------------------------------------

--
-- Copyright (c) 2026, Mupen64 Organization (https://github.com/mupen64)
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

---@class Color
---@field public r integer The red channel in the range 0 - 255.
---@field public g integer The green channel in the range 0 - 255.
---@field public b integer The blue channel in the range 0 - 255.
---@field public a integer? The alpha channel in the range 0 - 255. If nil, 255 is assumed.

---@class FloatColor
---@field public r number The red channel in the range 0.0 - 1.0.
---@field public g number The green channel in the range 0.0 - 1.0.
---@field public b number The blue channel in the range 0.0 - 1.0.
---@field public a number? The alpha channel in the range 0.0 - 1.0. If nil, 1.0 is assumed.

---@alias ArrayColor { [1]: integer, [2]: integer, [3]: integer, [4]: integer? }
---An integer color array in the format `{r, g, b, a?}`, with channels in the range 0 - 255.

---@alias ArrayFloatColor { [1]: number, [2]: number, [3]: number, [4]: number? }
---An integer color array in the format `{r, g, b, a?}`, with channels in the range 0.0 - 1.0.

---@alias HexColor string
---A hexadecimal color string in the format `#RRGGBB` or `#RRGGBBAA`.

---@alias RawColor integer
---A raw color value in the format `0xRRGGBBAA`.

---@alias ColorSource Color|FloatColor|ArrayColor|ArrayFloatColor|HexColor|RawColor
---A color-providing object that can be converted to a Color.

---@class Vector2
---@field public x number The X component.
---@field public y number The Y component.

---@class Size
---@field public width number The width.
---@field public height number The height.

---@class Rectangle
---@field public x number The X coordinate.
---@field public y number The Y coordinate.
---@field public width number The width.
---@field public height number The height.

---@class TextStyle
---@field public is_bold boolean? Whether the text is bold. If nil, false is assumed.
---@field public is_italic boolean? Whether the text is italic. If nil, false is assumed.
---@field public clip boolean? Whether the text should be clipped to the bounding rectangle. If nil, false is assumed.
---@field public grayscale boolean? Whether the text should be drawn in grayscale. If nil, false is assumed.
---@field public aliased boolean? Whether the text should be drawn with no text filtering. If nil, false is assumed.
---@field public fit boolean? Whether the text should be resized to fit the bounding rectangle. If nil, false is assumed.

---@class DrawTextParams
---@field public text string? The text. If nil, no text will be drawn.
---@field public rectangle Rectangle The text's bounding rectangle.
---@field public color ColorSource The text color.
---@field public font_name string The font name.
---@field public font_size number The font size.
---@field public align_x Alignment? The text's horizontal alignment inside the bounding rectangle. If nil, Alignment.center is assumed.
---@field public align_y Alignment? The text's vertical alignment inside the bounding rectangle. If nil, Alignment.center is assumed.
---@field public is_bold boolean? Whether the text is bold. If nil, false is assumed.
---@field public is_italic boolean? Whether the text is italic. If nil, false is assumed.
---@field public clip boolean? Whether the text should be clipped to the bounding rectangle. If nil, false is assumed.
---@field public grayscale boolean? Whether the text should be drawn in grayscale. If nil, false is assumed.
---@field public aliased boolean? Whether the text should be drawn with no text filtering. If nil, false is assumed.
---@field public fit boolean? Whether the text should be resized to fit the bounding rectangle. If nil, false is assumed.

---@class DrawImageParams
---@field public path string The image's absolute path on disk.
---@field public destx1 number The x-coordinate of the top-left corner of the destination rectangle.
---@field public desty1 number The y-coordinate of the top-left corner of the destination rectangle.
---@field public destx2 number? The x-coordinate of the bottom-right corner of the destination rectangle. If `nil`, `destx1` plus the natural width of the image is assumed.
---@field public desty2 number? The y-coordinate of the bottom-right corner of the destination rectangle. If `nil`, `desty1` plus the natural height of the image is assumed.
---@field public srcx1 number? The x-coordinate of the top-left corner of the source rectangle. If `nil`, `0` is assumed.
---@field public srcy1 number? The y-coordinate of the top-left corner of the source rectangle. If `nil`, `0` is assumed.
---@field public srcx2 number? The x-coordinate of the bottom-right corner of the source rectangle. If `nil`, `srcx1` plus the natural width of the image is assumed.
---@field public srcy2 number? The y-coordinate of the bottom-right corner of the source rectangle. If `nil`, `srcy1` plus the natural height of the image is assumed.
---@field public color ColorSource? The color to tint the image with. The RGB components are treated as multipliers after conversion to range 0-1, and the alpha component is treated as the opacity. If `nil`, the image is drawn without tinting.
---@field public interpolation integer? The interpolation mode to use. 0: nearest neighbor, 1|nil: linear.

---@class ImageInfo
---@field public width number The width.
---@field public height number The height.
---Contains information about an image.

---@enum StandardColors
--- A table of standard colors.
BreitbandGraphics.colors = {
    --- The color white.
    white = {
        r = 255,
        g = 255,
        b = 255,
    },

    --- The color black.
    black = {
        r = 0,
        g = 0,
        b = 0,
    },

    --- The color red.
    red = {
        r = 255,
        g = 0,
        b = 0,
    },

    --- The color green.
    green = {
        r = 0,
        g = 255,
        b = 0,
    },

    --- The color blue.
    blue = {
        r = 0,
        g = 0,
        b = 255,
    },

    --- The color yellow.
    yellow = {
        r = 255,
        g = 255,
        b = 0,
    },

    --- The color orange.
    orange = {
        r = 255,
        g = 128,
        b = 0,
    },

    --- The color magenta.
    magenta = {
        r = 255,
        g = 0,
        b = 255,
    },
}

---@enum Alignment
--- The alignment inside a container.
BreitbandGraphics.alignment = {
    --- The item is aligned to the start of the container.
    start = 1,
    --- The item is aligned to the center of the container.
    center = 2,
    --- The item is aligned to the end of the container.
    ['end'] = 3,
    --- The item is stretched to fill the container.
    stretch = 4,
}

-- ------------------------------------------------------------
--   src/BreitbandGraphics/internal.lua
-- ------------------------------------------------------------

--
-- Copyright (c) 2026, Mupen64 Organization (https://github.com/mupen64)
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

BreitbandGraphics.internal = {
    ---@type table<string, PainterImage>
    ---Map of image paths to decoded images.
    images = {},

    --- Creates a FloatColor from a Color.
    --- Channels with nil values will be converted to `0.0`, unless they are the alpha channel, in which case it will be converted to `1.0`.
    --- @param color Color The color to be converted.
    --- @return FloatColor # The color with remapped channels.
    color_to_float = function(color)
        return {
            r = (color.r and (color.r / 255.0) or 0.0),
            g = (color.g and (color.g / 255.0) or 0.0),
            b = (color.b and (color.b / 255.0) or 0.0),
            a = (color.a and (color.a / 255.0) or 1.0),
        }
    end,

    ---Convers a color source to a FloatColor.
    ---@param source ColorSource The color source.
    ---@return FloatColor # The converted color.
    color_source_to_float_color = function(source)
        -- Match RawColor
        if math.type(source) == "integer" then
            return {
                r = ((source >> 24) & 0xFF) / 255.0,
                g = ((source >> 16) & 0xFF) / 255.0,
                b = ((source >> 8) & 0xFF) / 255.0,
                a = (source & 0xFF) / 255.0,
            }
        end

        -- Match HexColor
        if type(source) == 'string' then
            return BreitbandGraphics.internal.color_to_float(BreitbandGraphics.hex_to_color(source))
        end

        -- Match ArrayColor and ArrayFloatColor
        if source[1] or source[2] or source[3] or source[4] then
            -- Match ArrayFloatColor
            if math.type(source[1]) == 'float' or math.type(source[2]) == 'float' or math.type(source[3]) == 'float' then
                return {
                    r = source[1] or 0.0,
                    g = source[2] or 0.0,
                    b = source[3] or 0.0,
                    a = source[4] or 1.0,
                }
            end

            -- Match ArrayColor
            return BreitbandGraphics.internal.color_to_float({
                r = source[1] or 0,
                g = source[2] or 0,
                b = source[3] or 0,
                a = source[4] or 255,
            })
        end

        -- Match FloatColor
        if math.type(source.r) == 'float' or math.type(source.g) == 'float' or math.type(source.b) == 'float' then
            return {
                r = source.r and source.r or 0.0,
                g = source.g and source.g or 0.0,
                b = source.b and source.b or 0.0,
                a = source.a and source.a or 1.0,
            }
        end

        -- Match Color
        if math.type(source.r) == 'integer' or math.type(source.g) == 'integer' or math.type(source.b) == 'integer' then
            return BreitbandGraphics.internal.color_to_float(source)
        end

        if type(source) == "table" then
            return BreitbandGraphics.internal.color_to_float({})
        end

        print('Invalid color source:')
        print(source)
        error('See above.')
    end,

    ---Converts a color source to the painter API's color table type.
    ---@param source ColorSource The color source.
    ---@return PainterColorTable # The converted color.
    color_source_to_painter_color = function(source)
        local color = BreitbandGraphics.internal.color_source_to_float_color(source)
        return {
            r = color.r,
            g = color.g,
            b = color.b,
            a = color.a,
        }
    end,

    ---Gets an image from a path, loading and caching it if necessary.
    ---@param path string The path to the image.
    ---@return PainterImage # The decoded image.
    image_from_path = function(path)
        local cached_image = BreitbandGraphics.internal.images[path]
        if cached_image then
            return cached_image
        end

        local image, error_message = painter.load_image(path)
        if not image then
            error(error_message or ('failed to load image: ' .. path), 2)
        end
        BreitbandGraphics.internal.images[path] = image
        ---@cast image PainterImage
        return image
    end,
}

-- ------------------------------------------------------------
--   src/BreitbandGraphics/core.lua
-- ------------------------------------------------------------

--
-- Copyright (c) 2026, Mupen64 Organization (https://github.com/mupen64)
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

--- Converts a color to its corresponding hexadecimal representation.
--- @param color ColorSource The color source to convert.
--- @returns string # The hexadecimal representation of the color.
BreitbandGraphics.color_to_hex = function(color)
    local converted = BreitbandGraphics.float_to_color(BreitbandGraphics.internal.color_source_to_float_color(color))
    return string.format('#%06X', (converted.r * 0x10000) + (converted.g * 0x100) + converted.b)
end

--- Converts a color's hexadecimal representation into a color table.
--- @param hex string The hexadecimal color to convert.
--- @return Color # The color.
BreitbandGraphics.hex_to_color = function(hex)
    if #hex > 7 then
        return
        {
            r = tonumber(hex:sub(2, 3), 16),
            g = tonumber(hex:sub(4, 5), 16),
            b = tonumber(hex:sub(6, 7), 16),
            a = tonumber(hex:sub(8, 9), 16),
        }
    end
    return
    {
        r = tonumber(hex:sub(2, 3), 16),
        g = tonumber(hex:sub(4, 5), 16),
        b = tonumber(hex:sub(6, 7), 16),
    }
end

--- Creates a color with the red, green and blue channels assigned to the specified value.
--- @param value number The value to be used for the red, green and blue channels.
--- @return Color # The color with the red, green and blue channels set to the specified value.
BreitbandGraphics.repeated_to_color = function(value)
    return
    {
        r = value,
        g = value,
        b = value,
    }
end

---Inverts a color source.
---@param color ColorSource The color source to invert.
---@return Color # The new inverted color.
BreitbandGraphics.invert_color = function(color)
    local converted = BreitbandGraphics.internal.color_source_to_float_color(color)
    return BreitbandGraphics.float_to_color({
        r = 1.0 - converted.r,
        g = 1.0 - converted.g,
        b = 1.0 - converted.b,
        a = converted.a,
    })
end

--- Creates a FloatColor from a ColorSource.
--- Channels with nil values will be converted to `0.0`, unless they are the alpha channel, in which case it will be converted to `1.0`.
--- @param color ColorSource The color to be converted.
--- @return FloatColor # The color with remapped channels.
BreitbandGraphics.color_to_float = function(color)
    return BreitbandGraphics.internal.color_source_to_float_color(color)
end

--- Creates a Color from a FloatColor.
--- Channels with nil values will be converted to `0`, unless they are the alpha channel, in which case it will be converted to `255`.
--- @param color FloatColor The color to be converted.
--- @return Color # The color with remapped channels.
BreitbandGraphics.float_to_color = function(color)
    return {
        r = (color.r and (math.tointeger(math.floor(color.r * 255 + 0.5))) or 0),
        g = (color.g and (math.tointeger(math.floor(color.g * 255 + 0.5))) or 0),
        b = (color.b and (math.tointeger(math.floor(color.b * 255 + 0.5))) or 0),
        a = (color.a and (math.tointeger(math.floor(color.a * 255 + 0.5))) or 255),
    }
end

---Checks whether a point is inside a rectangle.
---@param point Vector2 The point.
---@param rectangle Rectangle The rectangle.
---@return boolean # Whether the point is inside the rectangle.
BreitbandGraphics.is_point_inside_rectangle = function(point, rectangle)
    return point.x > rectangle.x and
        point.y > rectangle.y and
        point.x < rectangle.x + rectangle.width and
        point.y < rectangle.y + rectangle.height
end

---Checks whether a point is inside any of the rectangles.
---@param point Vector2 The point.
---@param rectangles Rectangle[] The rectangles.
---@return boolean # Whether the point is inside any of the rectangles.
BreitbandGraphics.is_point_inside_any_rectangle = function(point, rectangles)
    for i = 1, #rectangles, 1 do
        if BreitbandGraphics.is_point_inside_rectangle(point, rectangles[i]) then
            return true
        end
    end
    return false
end

--- Creates a rectangle inflated around its center by the specified amount.
--- @param rectangle Rectangle The rectangle to be inflated.
--- @param amount number The amount to inflate the rectangle by.
--- @return Rectangle # The inflated rectangle.
BreitbandGraphics.inflate_rectangle = function(rectangle, amount)
    return {
        x = rectangle.x - amount,
        y = rectangle.y - amount,
        width = rectangle.width + amount * 2,
        height = rectangle.height + amount * 2,
    }
end


---Draws a nineslice-scalable image with the specified parameters.
---@param destination_rectangle Rectangle The destination rectangle on the screen.
---@param source_rectangle Rectangle The source rectangle from the image.
---@param source_rectangle_center Rectangle The source rectangle for the center of the image.
---@param path string The image's absolute path on disk.
---@param color ColorSource The color filter applied to the image. If white, the image is drawn as-is.
---@param filter "nearest" | "linear" The texture filter applied to the image.
BreitbandGraphics.draw_image_nineslice = function(destination_rectangle, source_rectangle, source_rectangle_center, path,
    color, filter)
    destination_rectangle = {
        x = math.floor(destination_rectangle.x),
        y = math.floor(destination_rectangle.y),
        width = math.ceil(destination_rectangle.width),
        height = math.ceil(destination_rectangle.height),
    }
    source_rectangle = {
        x = math.floor(source_rectangle.x),
        y = math.floor(source_rectangle.y),
        width = math.ceil(source_rectangle.width),
        height = math.ceil(source_rectangle.height),
    }

    local image = BreitbandGraphics.internal.image_from_path(path)
    local options = {
        source = {
            x = source_rectangle.x,
            y = source_rectangle.y,
            w = source_rectangle.width,
            h = source_rectangle.height,
        },
        center = {
            x = source_rectangle_center.x,
            y = source_rectangle_center.y,
            w = source_rectangle_center.width,
            h = source_rectangle_center.height,
        },
        sampling = filter == 'linear' and 'linear' or 'nearest',
    }

    if color then
        local painter_color = BreitbandGraphics.internal.color_source_to_painter_color(color)
        options.tint = {
            r = painter_color.r,
            g = painter_color.g,
            b = painter_color.b,
            a = 1,
        }
        options.opacity = painter_color.a
    end

    painter.current():image(image, {
        x = destination_rectangle.x,
        y = destination_rectangle.y,
        w = destination_rectangle.width,
        h = destination_rectangle.height,
    }, options)
end

---Computes the bounding box of a text string given a font size and font name.
---@param text string The string to be measured.
---@param font_size number The font size.
---@param font_name string The font name.
---@return Size # The text's bounding box.
BreitbandGraphics.get_text_size = function(text, font_size, font_name)
    local metrics = painter.measure_text(text, {
        family = font_name,
        size = font_size,
    })
    return {
        width = metrics.w,
        height = metrics.h,
    }
end

local function fit_text(text, font_name, font_size, rectangle)
    local text_size = BreitbandGraphics.get_text_size(text, font_size, font_name)
    if text_size.width > rectangle.width then
        font_size = font_size / math.max(0.01, text_size.width / rectangle.width)
    end
    if text_size.height > rectangle.height then
        font_size = font_size / math.max(0.01, text_size.height / rectangle.height)
    end
    return font_size, BreitbandGraphics.get_text_size(text, font_size, font_name)
end

---@param alignment Alignment
---@return PainterTextHorizontalAlign
local function painter_text_horizontal_alignment(alignment)
    return alignment == BreitbandGraphics.alignment.center and 'center' or
        alignment == BreitbandGraphics.alignment['end'] and 'right' or
        alignment == BreitbandGraphics.alignment.stretch and 'justify' or 'left'
end

---@param alignment Alignment
---@return PainterTextVerticalAlign
local function painter_text_vertical_alignment(alignment)
    return alignment == BreitbandGraphics.alignment.center and 'center' or
        alignment == BreitbandGraphics.alignment['end'] and 'bottom' or 'top'
end

---Draws a rectangle's outline.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The outline's color.
---@param thickness number The outline's thickness.
BreitbandGraphics.draw_rectangle = function(rectangle, color, thickness)
    local p = painter.current()
    p:begin_path()
    p:rect({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    })
    p:stroke(BreitbandGraphics.internal.color_source_to_painter_color(color), {width = thickness})
end

---Draws a filled-in rectangle.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The fill color.
BreitbandGraphics.fill_rectangle = function(rectangle, color)
    local p = painter.current()
    p:begin_path()
    p:rect({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    })
    p:fill(BreitbandGraphics.internal.color_source_to_painter_color(color))
end

---Draws a rounded rectangle's outline.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The outline's color.
---@param radii Vector2 The corner radii.
---@param thickness number The outline's thickness.
BreitbandGraphics.draw_rounded_rectangle = function(rectangle, color, radii, thickness)
    local p = painter.current()
    p:begin_path()
    p:round_rect({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    }, math.min(radii.x, radii.y))
    p:stroke(BreitbandGraphics.internal.color_source_to_painter_color(color), {width = thickness})
end

---Draws a filled-in rounded rectangle.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The fill color.
---@param radii Vector2 The corner radii.
BreitbandGraphics.fill_rounded_rectangle = function(rectangle, color, radii)
    local p = painter.current()
    p:begin_path()
    p:round_rect({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    }, math.min(radii.x, radii.y))
    p:fill(BreitbandGraphics.internal.color_source_to_painter_color(color))
end

---Draws an ellipse's outline.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The outline's color.
---@param thickness number The outline's thickness.
BreitbandGraphics.draw_ellipse = function(rectangle, color, thickness)
    local p = painter.current()
    p:begin_path()
    p:circle({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    })
    p:stroke(BreitbandGraphics.internal.color_source_to_painter_color(color), {width = thickness})
end

---Draws a filled-in ellipse.
---@param rectangle Rectangle The shape's bounding rectangle.
---@param color ColorSource The fill color.
BreitbandGraphics.fill_ellipse = function(rectangle, color)
    local p = painter.current()
    p:begin_path()
    p:circle({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    })
    p:fill(BreitbandGraphics.internal.color_source_to_painter_color(color))
end

---Draws text with the specified parameters.
---Deprecated, use `draw_text2` instead.
---@param rectangle Rectangle The text's bounding rectangle.
---@param horizontal_alignment "center"|"start"|"end"|"stretch" The text's horizontal alignment inside the bounding rectangle.
---@param vertical_alignment "center"|"start"|"end"|"stretch" The text's vertical alignment inside the bounding rectangle.
---@param style TextStyle The text style options.
---@param color ColorSource The text color.
---@param font_size number The font size.
---@param font_name string The font name.
---@param text string The text.
---@deprecated
BreitbandGraphics.draw_text = function(rectangle, horizontal_alignment, vertical_alignment, style, color, font_size,
    font_name,
    text)
    if text == nil then
        text = ''
    elseif type(text) ~= 'string' then
        text = tostring(text)
    end

    local rect_x = rectangle.x
    local rect_y = rectangle.y
    local rect_w = rectangle.width
    local rect_h = rectangle.height
    local align_x = horizontal_alignment == 'center' and 'center' or
        horizontal_alignment == 'end' and 'right' or
        horizontal_alignment == 'stretch' and 'justify' or 'left'
    local align_y = vertical_alignment == 'center' and 'center' or
        vertical_alignment == 'end' and 'bottom' or 'top'

    if style.fit then
        local fitted_font_size, text_size = fit_text(text, font_name, font_size, rectangle)
        font_size = fitted_font_size
        if horizontal_alignment == 'center' or horizontal_alignment == 'stretch' then
            rect_x = rect_x + rect_w / 2 - text_size.width / 2
        elseif horizontal_alignment == 'end' then
            rect_x = rect_x + rect_w - text_size.width
        end
        if vertical_alignment == 'center' or vertical_alignment == 'stretch' then
            rect_y = rect_y + rect_h / 2 - text_size.height / 2
        elseif vertical_alignment == 'end' then
            rect_y = rect_y + rect_h - text_size.height
        end
        align_x = 'left'
        align_y = 'top'
        rect_w = text_size.width + 1
        rect_h = text_size.height + 1
    end

    local p = painter.current()
    p:begin_path()
    p:text(text, {x = rect_x, y = rect_y, w = rect_w, h = rect_h}, {
        family = font_name,
        size = font_size,
        weight = style.is_bold and 700 or 400,
        slant = style.is_italic and 'italic' or 'normal',
        align_x = align_x,
        align_y = align_y,
        antialiased = not style.aliased,
        overflow = style.clip and 'clip' or 'visible',
        clip = style.clip or false,
    })
    p:fill(BreitbandGraphics.internal.color_source_to_painter_color(color))
end

---Draws text with the specified parameters.
---@param params DrawTextParams The text drawing parameters.
BreitbandGraphics.draw_text2 = function(params)
    if not params.text then
        return
    end

    local rect_x = params.rectangle.x
    local rect_y = params.rectangle.y
    local rect_w = params.rectangle.width
    local rect_h = params.rectangle.height
    local align_x = params.align_x or BreitbandGraphics.alignment.center
    local align_y = params.align_y or BreitbandGraphics.alignment.center
    local font_size = params.font_size
    local text = type(params.text) == 'string' and params.text or tostring(params.text)

    if params.fit then
        local fitted_font_size, text_size = fit_text(text, params.font_name, font_size, params.rectangle)
        font_size = fitted_font_size
        if align_x == BreitbandGraphics.alignment.center or align_x == BreitbandGraphics.alignment.stretch then
            rect_x = rect_x + rect_w / 2 - text_size.width / 2
        elseif align_x == BreitbandGraphics.alignment['end'] then
            rect_x = rect_x + rect_w - text_size.width
        end
        if align_y == BreitbandGraphics.alignment.center or align_y == BreitbandGraphics.alignment.stretch then
            rect_y = rect_y + rect_h / 2 - text_size.height / 2
        elseif align_y == BreitbandGraphics.alignment['end'] then
            rect_y = rect_y + rect_h - text_size.height
        end
        rect_w = text_size.width + 1
        rect_h = text_size.height + 1
        align_x = BreitbandGraphics.alignment.start
        align_y = BreitbandGraphics.alignment.start
    end

    local p = painter.current()
    p:begin_path()
    p:text(text, {x = rect_x, y = rect_y, w = rect_w, h = rect_h}, {
        family = params.font_name,
        size = font_size,
        weight = params.is_bold and 700 or 400,
        slant = params.is_italic and 'italic' or 'normal',
        align_x = painter_text_horizontal_alignment(align_x),
        align_y = painter_text_vertical_alignment(align_y),
        antialiased = not params.aliased,
        overflow = params.clip and 'clip' or 'visible',
        clip = params.clip or false,
    })
    p:fill(BreitbandGraphics.internal.color_source_to_painter_color(params.color))
end

---Draws a line between two points.
---@param from Vector2 The start point.
---@param to Vector2 The end point.
---@param color ColorSource The line's color.
---@param thickness number The line's thickness.
BreitbandGraphics.draw_line = function(from, to, color, thickness)
    local p = painter.current()
    p:begin_path()
    p:line(from.x, from.y, to.x, to.y)
    p:stroke(BreitbandGraphics.internal.color_source_to_painter_color(color), {width = thickness})
end

---Pushes a clip layer to the clip stack.
---@param rectangle Rectangle The clip bounds.
BreitbandGraphics.push_clip = function(rectangle)
    local p = painter.current()
    p:save()
    p:clip({
        x = rectangle.x,
        y = rectangle.y,
        w = rectangle.width,
        h = rectangle.height,
    })
end

--- Removes the topmost clip layer from the clip stack.
BreitbandGraphics.pop_clip = function()
    painter.current():restore()
end

---Draws an image with the specified parameters.
---@deprecated Use `BreitbandGraphics.draw_image2` instead.
---@param destination_rectangle Rectangle The destination rectangle on the screen.
---@param source_rectangle Rectangle? The source rectangle from the image. If nil, the whole image is taken as the source.
---@param path string The image's absolute path on disk.
---@param color ColorSource? The color filter applied to the image. If nil or white, the image is drawn with no tint.
---@param filter "nearest" | "linear" The texture filter applied to the image.
BreitbandGraphics.draw_image = function(destination_rectangle, source_rectangle, path, color, filter)
    if not filter then
        filter = 'nearest'
    end
    local float_color
    if color then
        float_color = BreitbandGraphics.internal.color_source_to_float_color(color)
    else
        float_color = BreitbandGraphics.colors.white
    end
    local interpolation = filter == 'nearest' and 0 or 1

    if not source_rectangle then
        local size = BreitbandGraphics.get_image_info(path)
        source_rectangle = {
            x = 0,
            y = 0,
            width = size.width,
            height = size.height,
        }
    end

    BreitbandGraphics.draw_image2({
        path = path,
        destx1 = destination_rectangle.x,
        desty1 = destination_rectangle.y,
        destx2 = destination_rectangle.x + destination_rectangle.width,
        desty2 = destination_rectangle.y + destination_rectangle.height,
        srcx1 = source_rectangle.x,
        srcy1 = source_rectangle.y,
        srcx2 = source_rectangle.x + source_rectangle.width,
        srcy2 = source_rectangle.y + source_rectangle.height,
        color = float_color,
        interpolation = interpolation,
    })
end

---Draws an image with the specified parameters.
---@param params DrawImageParams The parameters to use when drawing the image.
BreitbandGraphics.draw_image2 = function(params)
    local image = BreitbandGraphics.internal.image_from_path(params.path)
    ---@cast image PainterImage
    local destx2 = params.destx2 or params.destx1 + image.w
    local desty2 = params.desty2 or params.desty1 + image.h
    local srcx1 = params.srcx1 or 0
    local srcy1 = params.srcy1 or 0
    local srcx2 = params.srcx2 or srcx1 + image.w
    local srcy2 = params.srcy2 or srcy1 + image.h
    local options = {
        source = {
            x = srcx1,
            y = srcy1,
            w = srcx2 - srcx1,
            h = srcy2 - srcy1,
        },
        sampling = params.interpolation == 0 and 'nearest' or 'linear',
    }

    if params.color then
        local color = BreitbandGraphics.internal.color_source_to_painter_color(params.color)
        options.tint = {r = color.r, g = color.g, b = color.b, a = 1}
        options.opacity = color.a
    end

    painter.current():image(image, {
        x = params.destx1,
        y = params.desty1,
        w = destx2 - params.destx1,
        h = desty2 - params.desty1,
    }, options)
end

---Gets information about an image.
---@param path string The image's absolute path on disk.
---@return ImageInfo # Information about the image.
BreitbandGraphics.get_image_info = function(path)
    local image = BreitbandGraphics.internal.image_from_path(path)
    ---@cast image PainterImage
    return {
        width = image.w,
        height = image.h,
    }
end

---Releases allocated resources.
---Must be called before stopping the Lua environment.
BreitbandGraphics.free = function()
    for path, image in pairs(BreitbandGraphics.internal.images) do
        ---@cast image PainterImage
        image:close()
        BreitbandGraphics.internal.images[path] = nil
    end
end

-- ------------------------------------------------------------
--   src/BreitbandGraphics/epilogue.lua
-- ------------------------------------------------------------

--
-- Copyright (c) 2026, Mupen64 Organization (https://github.com/mupen64)
--
-- SPDX-License-Identifier: GPL-3.0-or-later
--

return BreitbandGraphics
