name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync-stable:
    strategy:
      matrix:
        platform:
          - windows-x86
          - windows-x64
        include:
          - platform: windows-x86
            old_name: mupen64-w32
          - platform: windows-x64
            old_name: mupen64-w64

    uses: ./.github/workflows/sync-target.yml
    with:
      target: stable-${{ matrix.platform }}
      mode: stable
      asset: mupen64-${{ matrix.platform }}.zip
      fallback-asset: ${{ matrix.old_name }}
      commit-message: "chore: sync stable releases [skip ci]"

  sync-nightly:
    strategy:
      matrix:
        platform:
          - windows-x86
          - windows-x64
        include:
          - platform: windows-x86
            old_name: mupen-release-nightly-w32
          - platform: windows-x64
            old_name: mupen-release-nightly-w64

    uses: ./.github/workflows/sync-target.yml
    with:
      target: nightly-${{ matrix.platform }}
      mode: nightly
      asset: mupen64-release-nightly-${{ matrix.platform }}
      fallback-asset: ${{ matrix.old_name }}
      commit-message: "chore: sync [skip ci]"